### ISSUE TITLE
Serenity Emailable HTML reports (single page reports) - Error in POM.XML (artifactId: serenity-navigator-report)

### ISSUE THREAD

**Issue by TarahMo** [serenity-bdd/serenity-rest-starter#8]
Hi John

As the next step - I am trying to set-up pom.xm based on the Custom Reporting documentation (https://serenity-bdd.github.io/theserenitybook/latest/extended-reports.html), so following steps 1 & 2 beow. My Goal is to generate 'Emailable HTML reports' (Serenity emailable single page reports). As I can access the email summary in a file called 'serenity-summary.html' in the target folder.

However, post step 1 - I have encountered an error "Dependency 'net.serenity-bdd:serenity-navigator-report:2.4.24' not found" in pom.xml.

While I did some troubleshooting,I noticed that the atest version for 'Serenity Navigator Report' under Maven repository is 2.3.13. I have tried replacing version to 2.3.13 for '<artifactId>serenity-navigator-report</artifactId>' but encountered the same error as above (with a different version number).

Please can you advise how I would possibly resolve this error ? 

Step 1: Added the below to pom.xml

![Capture PL](https://user-images.githubusercontent.com/85223433/120759772-fc7bb580-c530-11eb-8b4f-e40fe628b776.JPG)

Step 2: Run using Maven command - clean verify serenity:reports -Dserenity.reports=single-page-html

Note: I noticed a typo in the documentation (https://serenity-bdd.github.io/theserenitybook/latest/extended-reports.html) where version for artifactId is 'serenity.version' which was throwing an error. I have replaced the artifactId to 'serenity.maven.version' and one of the error is fine now but still having the pom error "'net.serenity-bdd:serenity-navigator-report:2.4.24' not found".

![pom xml (serenity emailable single page reports)](https://user-images.githubusercontent.com/85223433/120759292-7fe8d700-c530-11eb-8ce8-fafe605a32f2.JPG)

**Comment by wakaleo** [comment]
Just use `serenity-single-page-report`, drop the dependency on `serenity-navigator-report` (that shouldn't be there)

**Comment by TarahMo** [comment]
Perfect - that resolved the error & using maven goal "clean verify serenity:reports -Dserenity.reports=single-page-html" - I can access Serenity Summary Report via 'serenity-summary.html' file.

**Comment by TarahMo** [comment]
As the reported problem has been resolved - closing the issue.

thank you John for your continuous support.
